name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag profile-site
  
  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Deploy application
        run: |
          docker stop profile-site
          docker rm profile-site
          docker run -dp 3000:3000 --name profile-site profile-site
          docker image prune -f
